### ISSUE TITLE
Call to deprecated function ESMP_Finalize (2.10.rc2-nox)

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#107]
@dnadeau4 @doutriaux1 this seems like there is something that has not been removed:
```
/work/cmip5/fx/fx/basin/cmip5.CMCC-CESM.historical.r0i0p0.fx.ocn.fx.basin.ver-v20130416.latestX.WARN2.xml
Traceback (most recent call last):
  File "make_evsp.py", line 114, in <module>
    c.plot(tmp)
  File "/usr/local/anaconda2/envs/2.8.10.rc2-nox/lib/python2.7/site-packages/vcs/Canvas.py", line 2641, in plot
    a = self.__plot(arglist, keyargs)
  File "/usr/local/anaconda2/envs/2.8.10.rc2-nox/lib/python2.7/site-packages/vcs/Canvas.py", line 3970, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/usr/local/anaconda2/envs/2.8.10.rc2-nox/lib/python2.7/site-packages/vcs/VTKPlots.py", line 607, in plot
    vtk_backend_grid, vtk_backend_geo, **kargs))
  File "/usr/local/anaconda2/envs/2.8.10.rc2-nox/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 317, in plot
    self._plotInternal()
  File "/usr/local/anaconda2/envs/2.8.10.rc2-nox/lib/python2.7/site-packages/vcs/vcsvtk/meshfillpipeline.py", line 186, in _plotInternal
    c = self.getColorIndexOrRGBA(_colorMap, tmpColors[ct][0])
IndexError: list index out of range
/usr/local/anaconda2/envs/2.8.10.rc2-nox/lib/python2.7/site-packages/ESMF/interface/cbindings.py:147: DeprecationWarning: Call to deprecated function ESMP_Finalize.
  def ESMP_Finalize():
```

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 I can confirm this issue doesn't occur in `v2.8.0`

**Comment by dnadeau4** [comment]
I think this error is about the colormap, not `ESMP_Finalize`.  
```    
c = self.getColorIndexOrRGBA(_colorMap, tmpColors[ct][0])
IndexError: list index out of range
```
