### ISSUE TITLE
No boundary data error

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#108]
@dnadeau4 this issue appears similar to https://github.com/UV-CDAT/cdms/issues/107:
```
/work/cmip5/fx/fx/areacello/cmip5.bcc-csm1-1-m.piControl.r0i0p0.fx.ocn.fx.areacello.ver-v20130307.latestX.xml
Traceback (most recent call last):
  File "make_evsp.py", line 99, in <module>
    c.plot(tmp)
  File "/export/duro/anaconda2/envs/uvcdat280nox/lib/python2.7/site-packages/vcs/Canvas.py", line 2564, in plot
    a = self.__plot(arglist, keyargs)
  File "/export/duro/anaconda2/envs/uvcdat280nox/lib/python2.7/site-packages/vcs/Canvas.py", line 3679, in __plot
    arglist[0] = self._reconstruct_tv(arglist, keyargs)
  File "/export/duro/anaconda2/envs/uvcdat280nox/lib/python2.7/site-packages/vcs/Canvas.py", line 709, in _reconstruct_tv
    mesh = grid.getMesh()
  File "/export/duro/anaconda2/envs/uvcdat280nox/lib/python2.7/site-packages/cdms2/hgrid.py", line 236, in getMesh
    raise CDMSError, 'No boundary data is available for grid %s'%self.id
cdms2.error.CDMSError: No boundary data is available for grid grid_600
```

**Comment by dnadeau4** [comment]
This is a vcs issue, not sure why vcs is calling grid.getMesh().  A grid always have bounds in cdms.  as for #107  ESMP.Finalize does not exist in the latest esmpy.  @doutriaux1 told me that @danlipsa fixed this lately....

**Comment by doutriaux1** [comment]
@dnadeau4 @durack1 yes if it is a curvilinear grid vcs gets the mesh info in order to plot on native grid. I believe CF requires the bounds? So it fails. @durack1 please resubmit to vcs I will make sure it doesn't fail in this case but falls back to `ferret-like` behaviour i.e. just plot raw numpy array.

**Comment by doutriaux1** [comment]
@durack1 also we will try to make it plots on `point data` rather than `cell data` in suhc case. I believe there's an open issue for this already.
