### ISSUE TITLE
Mean function of TransientVariable does not preserve type

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#137]
`TransientVariable` types are missing an ability to return the median value - also the format of the outputs are different as below, they should return the same type - not `masked_array` for `mean` and `float` for `min` and `max`:
```
In [99]: var.median()
Traceback (most recent call last):
  File "<ipython-input-99-b34c6e62fc16>", line 1, in <module>
    var.median()
AttributeError: 'TransientVariable' object has no attribute 'median'
In [100]: var.mean()
Out[100]: 
SouthIndian
masked_array(data = 6.0249723833e-05,
             mask = False,
       fill_value = 1e+20)
In [101]: var.min()
Out[101]: 5.779719322483626e-05
In [102]: var.max()
Out[102]: 6.3207208930421391e-05
```
@dnadeau4 are these functions wrapped numpy, or are they duplicated in the `cdms` code?

**Comment by doutriaux1** [comment]
```python
In [3]: data = numpy.array([1,2,3,4,5,6])

In [4]: data.min()
Out[4]: 1

In [5]: data.max()
Out[5]: 6

In [6]: data.median()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-40793500eb14> in <module>()
----> 1 data.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'
```
TV are subclassing numpy.

**Comment by durack1** [comment]
@doutriaux1 the comment about type is still valid, so reopening:
```
In [6]: data = np.array([1,2,3,4,5])
In [7]: data.min()
Out[7]: 1
In [8]: data.max()
Out[8]: 5
In [9]: data.mean()
Out[9]: 3.0
In [10]: data = np.ma.array([1,2,3,4,5], mask=False)
In [11]: data.min()
Out[11]: 1
In [12]: data.max()
Out[12]: 5
In [13]: data.mean()
Out[13]: 3.0
In [14]: data.median()
Traceback (most recent call last):
  File "<ipython-input-14-40793500eb14>", line 1, in <module>
    data.median()
AttributeError: 'MaskedArray' object has no attribute 'median'
In [15]: np.median(data)
Out[15]: 3.0
```
It would also be nice to have the `median` function as part of the `TransientVariable`, so adding this (using the numpy.median function) would be great

**Comment by doutriaux1** [comment]
@durack1 not sure how you get your type
```python
In [7]: type(s)
Out[7]: cdms2.tvariable.TransientVariable

In [8]: type(s.min())
Out[8]: numpy.float32

In [9]: s2=MV2.masked_greater(s,56.)

In [10]: type(s2)
Out[10]: cdms2.tvariable.TransientVariable

In [11]: type(s2.min())
Out[11]: numpy.float32

In [12]: s2.min()
Out[12]: 0.0
```

**Comment by durack1** [comment]
@doutriaux1, add an s.mean() to your examples above

**Comment by doutriaux1** [comment]
```python
In [5]: type(s2.mean())
Out[5]: numpy.float64
```

**Comment by doutriaux1** [comment]
is that the `float64` that bothers you?

**Comment by doutriaux1** [comment]
@dnadeau4 I see the issue:
```python
In [6]: s3 = s.asma()

In [7]: s3.dtype
Out[7]: dtype('float32')

In [8]: type(s3.mean())
Out[8]: numpy.float32
```

pure numpy preserves type

thanks @durack1

**Comment by doutriaux1** [comment]
@durack1 I renamed the issue

**Comment by durack1** [comment]
@doutriaux1 no problem, it's a type problem (so numpy types) and also what it returns - the TransientVariable mean returns an ndarray, whereas TransientVariable min/max returns a float

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 and I was also hoping that the median function can be added alongside the mean function - numpy has it, it just has to be added to the TransientVariable code

**Comment by doutriaux1** [comment]
@durack numpydoes not seem to have it at the variable level
```python
In [9]: s3.median()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-7233fbf5f5a9> in <module>()
----> 1 s3.median()

AttributeError: 'MaskedArray' object has no attribute 'median'

In [11]: numpy.median(s3)
Out[11]: 68.695

```

@dnadeau4 also looks like we can't use numpy.ma.median directly on a TV so we will need to add MV2.median and make sure most numpy.ma funcs can work on TVs

```python
In [12]: numpy.ma.median(s)
/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/avariable.py:1231: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (numpy.newaxis in specs):
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-15792cec85ad> in <module>()
----> 1 numpy.ma.median(s)

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/numpy/ma/extras.pyc in median(a, axis, out, overwrite_input, keepdims)
    693 
    694     r, k = _ureduce(a, func=_median, axis=axis, out=out,
--> 695                     overwrite_input=overwrite_input)
    696     if keepdims:
    697         return r.reshape(k)

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/numpy/lib/function_base.pyc in _ureduce(a, func, **kwargs)
   3856         keepdim = [1] * a.ndim
   3857 
-> 3858     r = func(a, **kwargs)
   3859     return r, keepdim
   3860 

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/numpy/ma/extras.pyc in _median(a, axis, out, overwrite_input)
    714             asorted = a
    715     else:
--> 716         asorted = sort(a, axis=axis, fill_value=fill_value)
    717 
    718     if axis is None:

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/numpy/ma/core.pyc in sort(a, axis, kind, order, endwith, fill_value)
   6526                            indexing='ij')
   6527         indx[axis] = sindx
-> 6528     return a[indx]
   6529 sort.__doc__ = MaskedArray.sort.__doc__
   6530 

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/avariable.pyc in __getitem__(self, key)
   1496             if isinstance(key, types.IntType) and key >= len(self):
   1497                 raise IndexError("Index too large: %d" % key)
-> 1498             speclist = self._process_specs([key], {})
   1499 
   1500         # Note: raw=0 ensures that a TransientVariable is returned

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/avariable.pyc in _process_specs(self, specs, keys)
   1234             nnewaxis = 0
   1235 
-> 1236         if (Ellipsis in specs):
   1237             nellipses = 1
   1238         else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [13]: numpy.median(s)
---------------------------------------------------------------------------
CDMSError                                 Traceback (most recent call last)
<ipython-input-13-36bced5ba928> in <module>()
----> 1 numpy.median(s)

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/numpy/lib/function_base.pyc in median(a, axis, out, overwrite_input, keepdims)
   3942     """
   3943     r, k = _ureduce(a, func=_median, axis=axis, out=out,
-> 3944                     overwrite_input=overwrite_input)
   3945     if keepdims:
   3946         return r.reshape(k)

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/numpy/lib/function_base.pyc in _ureduce(a, func, **kwargs)
   3856         keepdim = [1] * a.ndim
   3857 
-> 3858     r = func(a, **kwargs)
   3859     return r, keepdim
   3860 

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/numpy/lib/function_base.pyc in _median(a, axis, out, overwrite_input)
   3994     if np.issubdtype(a.dtype, np.inexact) and sz > 0:
   3995         # warn and return nans like mean would
-> 3996         rout = mean(part[indexer], axis=axis, out=out)
   3997         return np.lib.utils._median_nancheck(part, rout, axis, out)
   3998     else:

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/avariable.pyc in __getitem__(self, key)
   1499 
   1500         # Note: raw=0 ensures that a TransientVariable is returned
-> 1501         return self.getSlice(numericSqueeze=1, raw=0, isitem=1, *speclist)
   1502 
   1503     def __getslice__(self, low, high):

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/avariable.pyc in getSlice(self, *specs, **keys)
    709         keys['grid'] = keys.get('grid', None)
    710         isitem = keys.get('isitem', 0)
--> 711         result = self.subSlice(*specs, **keys)
    712 
    713         # return a scalar for 0-D slices

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/avariable.pyc in subSlice(self, *specs, **keys)
    595         else:
    596             singles = None
--> 597         slicelist = self.specs2slices(speclist, force=1)
    598         d = self.expertSlice(slicelist)
    599         squeeze = keys.get('squeeze', 0)

/Users/doutriaux1/anaconda2/envs/2.10/lib/python2.7/site-packages/cdms2/avariable.pyc in specs2slices(self, speclist, force)
   1312                 slicelist.append(slice(*key))
   1313             else:
-> 1314                 raise CDMSError('invalid index: %s' % str(key))
   1315         # Change default or negative start, stop to positive
   1316         for i in range(self.rank()):

CDMSError: invalid index: [slice(198719, 198721, None)]

In [14]: 
```

**Comment by doutriaux1** [comment]
@dnadeau4 this latest part (numpy.ma) is probably related to #55

**Comment by durack1** [comment]
@doutriaux1 yeah you're right, it's not implemented as an object function, so you can call numpyVariable.min() or mean or max, but you need to call numpy.median(numpyVariable) which is not really consistent - it doesn't mean that a TransientVariable can't wrap this function in a cleaner way though.. And this is what I am advocating

**Comment by doutriaux1** [comment]
@dnadeau4 did . you have a chance to take a look at this?  I can't remember?

**Comment by dnadeau4** [comment]
No I have not...This is priority 4...

**Comment by doutriaux1** [comment]
no worries, just checking

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 this is a valid issue, so have removed the `invalid` label
