### ISSUE TITLE
Inconsistent/weird error message when opening a non-existing file

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdms#148]
@dnadeau4 I get the following traceback when opening a non existing file, in **2.10**
```
(cdatm15) bash-4.1$ python
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdms2
>>> f = cdms2.open('./does_not_exist.nc')
CDMS system error: No such file or directory
CDMS I/O error: Opening file /home/users/jypeter/CDAT/Progs/Devel/matplotlib/Grids/does_not_exist.nc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm15/lib/python2.7/site-packages/cdms2/dataset.py", line 357, in openDataset
    return CdmsFile(path, mode, mpiBarrier=CdMpi)
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm15/lib/python2.7/site-packages/cdms2/dataset.py", line 1090, in __init__
    raise CDMSError('Cannot open file %s (%s)' % (path, err))
cdms2.error.CDMSError: Cannot open file /home/users/jypeter/CDAT/Progs/Devel/matplotlib/Grids/does_not_exist.nc (No error)
```
The message at the top (_CDMS system error: No such file or directory_) is OK, but the one at the bottom is strange: Cannot open file ...  **(No error)**

In another python interpreter, after running a real script, I get the same correct message at the top, and a slightly different, but still strange message at the bottom:  Cannot open file  **(Variable not found)**
```
>>> g = cdms2.open('./does_not_exist.nc')
CDMS system error: No such file or directory
CDMS I/O error: Opening file /home/users/jypeter/CDAT/Progs/Devel/lmissi/does_not_exist.nc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm15/lib/python2.7/site-packages/cdms2/dataset.py", line 357, in openDataset
    return CdmsFile(path, mode, mpiBarrier=CdMpi)
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm15/lib/python2.7/site-packages/cdms2/dataset.py", line 1090, in __init__
    raise CDMSError('Cannot open file %s (%s)' % (path, err))
cdms2.error.CDMSError: Cannot open file /home/users/jypeter/CDAT/Progs/Devel/lmissi/does_not_exist.nc (Variable not found)

```

**Comment by dnadeau4** [comment]
908f9b8907eedf56389d5d8996ae84b76ab0f8c0
