### ISSUE TITLE
cdms2 fails to read a variable with an inconsistent missing/fill value

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdms#162]
@dnadeau4 one of my colleagues has a file with basin masks of type **byte** and **an inconsistent float missing value**
```
	byte medmsk(y, x) ;
		medmsk:units = "byte" ;
		medmsk:long_name = "mediterranean sea" ;
		medmsk:missing_value = 1.e+20f ;
```

Data file: [ORCA2.0_medmsk.zip](https://github.com/UV-CDAT/cdms/files/1245778/ORCA2.0_medmsk.zip)

Using 2.10, this leads to a long traceback when you try to read the variable
```
>>> import cdms2 
>>> f = cdms2.open('/home/scratch01/jypeter/ORCA2.0_medmsk.nc')
>>> f.listvariables()
['medmsk']
>>> medmsk = f('medmsk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 37, in __call__
    return v(*args, **kwargs)
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/cdms2/avariable.py", line 165, in __call__
    grid=grid)
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/cdms2/selectors.py", line 208, in unmodified_select
    grid=grid, raw=raw)
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/cdms2/avariable.py", line 820, in subRegion
    return self.subSlice(*slicelist, **d)
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/cdms2/avariable.py", line 642, in subSlice
    resultArray = self._returnArray(d, squeeze, singles=singles)
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/cdms2/avariable.py", line 196, in _returnArray
    result = numpy.ma.masked_values(ar, missing, copy=0)
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/numpy/ma/core.py", line 2307, in masked_values
    return masked_array(xnew, mask=mask, copy=copy, fill_value=value)
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/numpy/ma/core.py", line 2877, in __new__
    _data._fill_value = _check_fill_value(fill_value, _data.dtype)
  File "/home/share/unix_files/cdat/miniconda2/envs/uvcdat-2.10/lib/python2.7/site-packages/numpy/ma/core.py", line 485, in _check_fill_value
    raise TypeError(err_msg % (fill_value, ndtype))
TypeError: Fill value 1.00000002004e+20 overflows dtype int8
```
My colleague said that _netcdf4_ can read the variable. The metadata is not consistent with the metadata, so an error is not unexpected but:
- is there a way to **override the error** and still read the data? I have tried `f('medmsk', raw=1)` and `f('medmsk', raw=True)` but I got the same error message
- could cdms2 trap/check/find this inconsistency and report this more gracefully to the user (possibly giving a hint how to override the error)?

Thanks!

**Comment by dnadeau4** [comment]
I guess  `missing_value` is now deprecated in [CF-1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#attribute-appendix) compliance.  `CDMS` is still back compatible using `missing_value` as `_FillValue` when encountered.    So if I drop `missing_value` in CDMS code, then your variable will be assigned a `_FillValue` to 1e20 by default by `numpy`.  Actually the error is coming from `numpy` since `CDMS` tried to assign your `missing_value` as `_FillValue`.   

I don't really want to do this, since some people use very old dataset for their research.   Your colleague should add a `_FillValue` attribute to his file to be CF-1 compliant.   netCDF library won't allow a `_FillValue` to be of a different type than the variable type.

**Comment by doutriaux1** [comment]
@dnadeau4 are we ensuring this as well? Is cdms2 ensuring missing_value/_FIllValue are casted to the same type as data? I think so, but we should double check.

**Comment by dnadeau4** [comment]
@doutriaux1 we do
```python
    def _setmissing(self, value):
        self._missing = numpy.array(value).astype(self.dtype)

    missing = property(_getmissing, _setmissing)
    fill_value = property(_getmissing, _setmissing)
    _FillValue = property(_getmissing, _setmissing)
    missing_value = property(_getmissing, _setmissing)
```

**Comment by dnadeau4** [comment]
@jypeter can you close this issue?
