### ISSUE TITLE
Non descriptive valueerrors generated when writing two variables with same name

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#197]
When two variables share the same `.id`, and a user attempts to write both variables out to the same netcdf file the errors reported do not provide any insight to a user. I was trying to ascertain what my problem was for quite sometime before I realised that I was trying to write two identically named variables into the same name space.

An example of the error is below:
```python
import cdms2 as cdm
cdm.setNetcdfShuffleFlag(1)
cdm.setNetcdfDeflateFlag(1)
cdm.setNetcdfDeflateLevelFlag(9)
cdm.setCompressionWarnings(0) ; # Suppress warning messages

f = '171116_thetao.nc'
fH = cdm.open(f)
thetao2dim = fH('thetao')
print 'thetao2dim.shape',thetao2dim.shape
print 'thetao2dim.id',thetao2dim.id
thetao1dim = thetao2dim[:,0,]
thetao1dim.id = 'thetao'
print 'thetao1dim.shape',thetao1dim.shape
print 'thetao1dim.id',thetao1dim.id
# Test write largest first
f1 = 'test1.nc'
f1H = cdm.open(f1,'w')
f1H.write(thetao2dim.astype('float32'))
f1H.write(thetao1dim.astype('float32')) ; # yields 'ValueError: shapes are not aligned'

#Traceback (most recent call last):
#  File "<ipython-input-7-fdfa8203ddee>", line 1, in <module>
#    f1H.write(thetao1dim.astype('float32'))
#  File "/export/duro/anaconda2/envs/uvcdat2120/lib/python2.7/site-packages/cdms2/dataset.py", line 2049, in write
#    v[index:index + len(vec1)] = var.astype(v.dtype)
#  File "/export/duro/anaconda2/envs/uvcdat2120/lib/python2.7/site-packages/cdms2/fvariable.py", line 137, in __setslice__
#    self._obj_.setslice(*(low, high, numpy.ma.filled(value)))
#ValueError: shapes are not aligned

f1H.close()
# Test write smallest first
f2 = 'test2.nc'
f2H = cdm.open(f2,'w')
f2H.write(thetao1dim.astype('float32'))
f2H.write(thetao2dim.astype('float32')) ; # yields 'ValueError: object too deep for desired array'

#Traceback (most recent call last):
#  File "<ipython-input-10-afb63fe204d2>", line 1, in <module>
#    f2H.write(thetao2dim.astype('float32'))
#  File "/export/duro/anaconda2/envs/uvcdat2120/lib/python2.7/site-packages/cdms2/dataset.py", line 2049, in write
#    v[index:index + len(vec1)] = var.astype(v.dtype)
#  File "/export/duro/anaconda2/envs/uvcdat2120/lib/python2.7/site-packages/cdms2/fvariable.py", line 137, in __setslice__
#    self._obj_.setslice(*(low, high, numpy.ma.filled(value)))
#ValueError: object too deep for desired array

f2H.close()
```
The data used above is attached below
[171116_thetao.nc.zip](https://github.com/UV-CDAT/cdms/files/1480260/171116_thetao.nc.zip)

In the example above, it would be useful for a user to trap and replace this error, indicating that two variables that have an identical name cannot be written to a file. If such an error was in place, it would have saved me considerable time

**Comment by jypeter** [comment]
Well, theoretically, with cdms, you can write multiple variables with an identical name to a file, when you are _extending_ a variable along the unlimited dimension (I guess the time axis, most of the time), so you want to be sure that you still allow this behavior. I've done some digging and found a 2007 Numeric based script where I was testing this behavior. I have attached this below, for the people who have not known the _good old times_ :)

```
#!/usr/bin/env python

import Numeric, cdms, MV, cdtime

#data = Numeric.ones((1, 10, 20), Numeric.Float32)
#timeval = Numeric.array((0.), Numeric.Float32)
#timax = cdms.createAxis((timeval,))
data = Numeric.ones((2, 10, 20), Numeric.Float32, savespace=1)
data[1, ...] *= 2
timeval = Numeric.array((0., 1.), Numeric.Float32)
timax = cdms.createAxis(timeval)

timax.id = 'time'
#timax.units = 'days since 2007-02-01'
timax.units = 'months since 2007-02-01'
timax.designateTime(cdtime.MixedCalendar)
latax = cdms.createUniformLatitudeAxis(0, 10, 1)
lonax = cdms.createUniformLongitudeAxis(0, 20, 1)

v1 = cdms.createVariable(data, axes=[timax, latax, lonax], id='v1')
tvals = v1.getTime()
v2 = v1.clone()
v2.id = 'v2'
v2[...] *= 10

f = cdms.open('/home/scratch01/jypeter/test_multi_write.nc', 'a')

## f.write(v1)
## f.write(v2)
## v1[...] *= 2
## timeval[0] = 1
## tvals.assignValue(timeval)
## f.write(v1)
## v1[...] *= 2
## timeval[0] = 0
## tvals.assignValue(timeval)
## f.write(v1, index=2)
## v1[...] *= 2
## f.write(v1, index=4)

## f.close()

#v1[...] *= 10
v1[...] = -1
f.write(v1)
## timeval[0] = 0
## timeval[1] = 3
## tvals.assignValue(timeval)
## #v1[...] *= 10
## f.write(v1)
timeval[0] = 11
timeval[1] = 20
tvals.assignValue(timeval)
v1[...] = 2
f.write(v1, index=1)

f.close()


# The end
```

**Comment by dnadeau4** [comment]
@jypeter this is still working fine.

```python
numpy, cdms2, MV2, cdtime


data = numpy.ones((2, 10, 20), numpy.float32 )
data[1, ...] *= 2
timeval = numpy.array((0., 1.), numpy.float32)
timax = cdms2.createAxis(timeval)

timax.id = 'time'

timax.units = 'months since 2007-02-01'
timax.designateTime(cdtime.MixedCalendar)
latax = cdms2.createUniformLatitudeAxis(0, 10, 1)
lonax = cdms2.createUniformLongitudeAxis(0, 20, 1)

v1 = cdms2.createVariable(data, axes=[timax, latax, lonax], id='v1')
tvals = v1.getTime()
v2 = v1.clone()
v2.id = 'v2'
v2[...] *= 10

f = cdms2.open('./test_multi_write.nc', 'w')

v1[...] = -1
f.write(v1)

timeval[0] = 11
timeval[1] = 20
tvals.assignValue(timeval)
v1[...] = 2
f.write(v1, index=1)

f.close()
```

**Comment by durack1** [comment]
@dnadeau4 is the example https://github.com/UV-CDAT/cdms/issues/197#issue-274666107 getting a better error message/warning to a user?
