### ISSUE TITLE
Problem finding hdf library from ESMF

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#198]
This error was generated with cdms2-2.10-np112py27_3 and ESMF esmf-7.0.0-7
```
(PMP-Cdat2120) duro@ocean:[170906_PaperPlots_OceanMetrics]:[7525]> pcmdi_metrics_driver.py -p cmip5_picontrol_pmp_parameterfile_thetao.py
Traceback (most recent call last):
  File "/export/duro/anaconda2/envs/PMP-Cdat2120/lib/python2.7/site-packages/ESMF/interface/loadESMF.py", line 122, in <module>
    mode=ct.RTLD_GLOBAL)
  File "/export/duro/anaconda2/envs/PMP-Cdat2120/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libhdf5_hl.so.100: cannot open shared object file: No such file or directory
```
cdms2-2.10-np112py27_3 is part of the current PMP1.1.2 release

**Comment by doutriaux1** [comment]
conda-forge messed up big time with new hdf5/netcdf

It seems that one can solve this with

```
conda install -f -c conda-forge netcdf-fortran =4.4.4=3
```

**Comment by dnadeau4** [comment]
I guess we will have to pin netcdf-fortran in the meta.yaml.

**Comment by doutriaux1** [comment]
on mac no issue though (at least today)

**Comment by dnadeau4** [comment]
netcdf-fortran=4.4.4=5 worked.

**Comment by doutriaux1** [comment]
@dnadeau4 failed on Linux travis. I had to take it off last night.
