### ISSUE TITLE
nightlies broken

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdms#245]
installing from nightly:
```
conda create -q -n py2 -c cdat/label/nightly -c conda-forge -c cdat cdms2 cdat_info udunits2 nose flake8 mesalib nose image-compare flake8 matplotlib image-compare genutil dv3d cdutil cdtime "proj4<5" "python<3" "numpy>1.14" 
```

```
The following NEW packages will be INSTALLED:

[snip]
    cdat_info:                     2.12.2018.03.21.14.44.g5d47bca-py27_0 cdat/label/nightly
    cdms2:                         3.0-py27_6                            conda-forge       
    cdtime:                        3.0-py27_0                            conda-forge       
    cdutil:                        8.0-py27_1                            conda-forge       
[snip]
    esmf:                          7.1.0r-1                              conda-forge       
    esmpy:                         7.1.0r-py27_1                         conda-forge       
[snip]
    lapack:                        3.6.1-1                               conda-forge       
    libcdms:                       3.0.1-1                               cdat/label/nightly
    libcf:                         1.0.1-py27_2                          conda-forge       
    libdrs:                        3.0-0                                 cdat/label/nightly
    libdrs_f:                      3.0-0                                 conda-forge       
    libffi:                        3.2.1-3                               conda-forge       
    libgcc:                        7.2.0-h69d50b8_2                                        
    libgcc-ng:                     7.2.0-hdf63c60_3                                        
    libgfortran:                   3.0.0-1                                                 
    libiconv:                      1.15-0                                conda-forge       
    libidn11:                      1.33-0                                conda-forge       
    libnetcdf:                     4.6.1-2                               conda-forge       
    libpng:                        1.6.34-0                              conda-forge       
[snip]
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id

done
Solving environment: ...working... done
```

runtime error:

```
E
======================================================================
ERROR: Failure: ImportError (libnetcdf.so.11: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/workspace/test_linux_vcs/miniconda/envs/py2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/circleci/project/workspace/test_linux_vcs/miniconda/envs/py2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/circleci/project/workspace/test_linux_vcs/miniconda/envs/py2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/circleci/project/tests/test_vcs_load_mpl_cmaps.py", line 2, in <module>
    import vcs
  File "/home/circleci/project/vcs/__init__.py", line 102, in <module>
    from .utils import *  # noqa
  File "/home/circleci/project/vcs/utils.py", line 17, in <module>
    import cdtime
ImportError: libnetcdf.so.11: cannot open shared object file: No such file or directory
----------------------------------------------------------------------
Ran 1 test in 0.002s
FAILED (errors=1)
E
```

**Comment by doutriaux1** [comment]
@muryanto1 this is why most nightlies will look broken today

**Comment by doutriaux1** [comment]
This seems to be Linux related only.

**Comment by dnadeau4** [comment]
@doutriaux1 I think we can close this issue.

**Comment by doutriaux1** [comment]
@muryanto1 please double check it close if it works. Thanks!

**Comment by muryanto1** [comment]
This bug is fixed in nightly.
