### ISSUE TITLE
Ignore extra slashes in input files in cdscan

### ISSUE THREAD

**Issue by pochedls** [CDAT/cdms#258]
Using cdscan (CDAT8 / Python 2):

cdscan -x test.xml /path/to/files//*.nc

The extra slash is included in the file names when the xml is written, which creates errors when opening the file. For example: 

> f = cdms2.open('test.xml')
> f.listvariable()
['pr', 'time_bnds', 'lon_bnds', 'lat_bnds']
> d = f('pr', time = slice(0,10))
CDMS system error: No such file or directory
CDMS I/O error: Opening file /pr_day_MIROC4h_historical_r1i1p1_19500101-19501231.nc

I currently have this fixed in my code: 

`cmd = 'cdscan -x ' + outfile + ' ' + inpath + '/*.nc'`
`cmd = cmd.replace('//', '/')`

But it would be worth adding something similar to cdscan. This issue has come up for me in the past and will likely arise for others.

**Comment by durack1** [comment]
The user output from this error looks like:
```
(pmp_8.0_2.7) bash-4.1$ python
Python 2.7.15 | packaged by conda-forge | (default, May  8 2018, 14:46:53)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdms2
>>> f = cdms2.open('/work/cmip5-test/new/historical/atmos/day/pr/cmip5.MIROC4h.historical.r1i1p1.day.atmos.day.pr.000000.v20120628.xml')
>>> f.listvariable()
['pr', 'time_bnds', 'lon_bnds', 'lat_bnds']
>>> d = f('pr', time = slice(0,10))
CDMS system error: No such file or directory
CDMS I/O error: Opening file /pr_day_MIROC4h_historical_r1i1p1_19500101-19501231.nc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export_backup/gleckler/anaconda2/envs/pmp_8.0_2.7/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 34, in __call__
    return v(*args, **kwargs)
  File "/export_backup/gleckler/anaconda2/envs/pmp_8.0_2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 170, in __call__
    grid=grid)
  File "/export_backup/gleckler/anaconda2/envs/pmp_8.0_2.7/lib/python2.7/site-packages/cdms2/selectors.py", line 187, in unmodified_select
    fetched = result.subRegion(*specifications)
  File "/export_backup/gleckler/anaconda2/envs/pmp_8.0_2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 824, in subRegion
    return self.subSlice(*slicelist, **d)
  File "/export_backup/gleckler/anaconda2/envs/pmp_8.0_2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 602, in subSlice
    d = self.expertSlice(slicelist)
  File "/export_backup/gleckler/anaconda2/envs/pmp_8.0_2.7/lib/python2.7/site-packages/cdms2/variable.py", line 566, in expertSlice
    f = self.parent.openFile(filename, 'r')
  File "/export_backup/gleckler/anaconda2/envs/pmp_8.0_2.7/lib/python2.7/site-packages/cdms2/dataset.py", line 934, in openFile
    f = Cdunif.CdunifFile(path, mode)
IOError: No error
```
