### ISSUE TITLE
Issue with level indexing

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#273]
I'm getting an error which doesn't appear easy to ascertain the cause:
```python
import cdms2 as cdm
filePath = 
'/work/durack1/Shared/cmip5/historical/ocn/an_trends/1950-2004/thetao_driftcorrect
/cmip5.ACCESS1-0.historical.r1i1p1.an.ocn.thetao.ver-1.1950-2004_ClimAndSlope.nc'
fH = cdm.open(filePath)
thetao = fH['thetao_change']
In [4]: upper = fH(thetao,level=(0,700))
Traceback (most recent call last):
  File "<ipython-input-4-89c7809a4796>", line 1, in <module>
    upper = fH(thetao,level=(0,700))
  File "anaconda2/envs/cdat80py2/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 33, in __call__
    raise CDMSError("No such variable, " + id)
  File "anaconda2/envs/cdat80py2/lib/python2.7/site-packages/cdms2/avariable.py", line 1533, in __add__
    return MV.add(self, other)
  File "anaconda2/envs/cdat80py2/lib/python2.7/site-packages/cdms2/MV2.py", line 246, in __call__
    maresult = self.mafunc(ta, tb, **kwargs)
  File "/anaconda2/envs/cdat80py2/lib/python2.7/site-packages/numpy/ma/core.py", line 1017, in __call__
    result = self.f(da, db, *args, **kwargs)
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')
```
I've attached an `ncdump -ct` from the file in the case this is a trivial problem
[cmip5.ACCESS1-0.historical.r1i1p1.an.ocn.thetao.ver-1.1950-2004_ClimAndSlope.txt](https://github.com/CDAT/cdms/files/2338430/cmip5.ACCESS1-0.historical.r1i1p1.an.ocn.thetao.ver-1.1950-2004_ClimAndSlope.txt)

And the relevant `cdms2` version is
```
(cdat80py2) duro@ocean:[180606_PaperPlots_UpperDeepWarming]:[8918]> ls -al anaconda2/envs/cdat80py2/conda-meta/*cdms*
-rw------- 1 duro climate  54K Jul 18 11:59 anaconda2/envs/cdat80py2/conda-meta/cdms2-3.0.1-py27h6091dcd_1.json
-rw------- 1 duro climate 4.7K Jul 18 11:59 anaconda2/envs/cdat80py2/conda-meta/libcdms-3.0.1-h9ac9557_2.json
```

**Comment by durack1** [comment]
Interesting, if I change the variable load type from:
```python
thetao = fH['thetao_change']
```
to:
```python
thetao = fH('thetao_change')
```
The error changes and becomes
```python
Traceback (most recent call last):
  File "make_modelMaps.py", line 27, in <module>
    upper = fH(thetao,level=(0,700))
  File "anaconda2/envs/cdat80py2/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 23, in __call__
    v = self.variables.get(id)
TypeError: unhashable type: 'TransientVariable'
```

**Comment by durack1** [comment]
The error appears to be reproducible back to 2.12:
```python
(uvcdat2120) duro@ocean:[180606_PaperPlots_UpperDeepWarming]:[8919]> python make_modelMaps.py
Traceback (most recent call last):
  File "make_modelMaps.py", line 27, in <module>
    upper = fH(thetao,level=(0,700))
  File "anaconda2/envs/uvcdat2120/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 26, in __call__
    v = self.variables.get(id)
TypeError: unhashable type: 'TransientVariable'
```
And the relevant `cdms2` version info for this:
```python
(uvcdat2120) duro@ocean:[180606_PaperPlots_UpperDeepWarming]:[8919]> ls anaconda2/envs/uvcdat2120/conda-meta/*cdms*
anaconda2/envs/uvcdat2120/conda-meta/cdms2-2.12-np113py27_0.json  anaconda2/envs/uvcdat2120/conda-meta/libcdms-2.12-0.json
```

**Comment by durack1** [comment]
@doutriaux1 apologies this was completely erroneous, I was trying to open a filehandle using a read variable as an input, my mistake, closing

**Comment by doutriaux1** [comment]
It was late in the day. No worries.
