### ISSUE TITLE
cdtime conda install failed

### ISSUE THREAD

**Issue by chengzhuzhang** [CDAT/cdms#300]
**Describe the bug**
I used to have instruction for install arm_diags with:
 ```
conda create -n arm_diags_env cdp=1.0.3 cdutil=2.10 genutil=2.10 cdms2=2.10 cdtime=2.10 numpy=1.12.1 matplotlib=2.0.2 scipy=0.19.1 -c conda-forge -c uvcdat
 ```
Today, when I try it again and run the package, I got following:
 
(arm_diags_env_v2) ml-9635225:arm_diags zhang40$ python arm_driver.py -p basicparameter.py
Traceback (most recent call last):
  File "arm_driver.py", line 5, in <module>
    import cdutil
  File "/Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdutil/__init__.py", line 3, in <module>
    from . import region  # noqa
  File "/Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdutil/region.py", line 2, in <module>
    from cdms2.selectors import SelectorComponent
  File "/Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdms2/__init__.py", line 20, in <module>
    from cdmsobj import CdArray, CdChar, CdByte, CdDouble, CdFloat, CdFromObject, CdInt, CdLong, CdScalar, CdShort, CdString
  File "/Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdms2/cdmsobj.py", line 5, in <module>
    import cdmsNode
  File "/Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdms2/cdmsNode.py", line 10, in <module>
    import cdtime
  File "/Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdtime/__init__.py", line 8, in <module>
    from .compreltime import *
  File "/Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdtime/compreltime.py", line 2, in <module>
    from . import _cdtime
ImportError: dlopen(/Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdtime/_cdtime.so, 2): Library not loaded: @rpath/libnetcdf.13.dylib
  Referenced from: /Users/zhang40/anaconda2/envs/arm_diags_env_v2/lib/python2.7/site-packages/cdtime/_cdtime.so
  Reason: image not found

@doutriaux1 also discovered same issue:
https://238-65930850-gh.circle-artifacts.com/0/tests_html/test_EzPlot_0.html

**Comment by chengzhuzhang** [comment]
It works linking libnetcdf.13.dylib to libnetcdf.11.dylib. Thanks @dnadeau4 !
```
ln -s /Users/zhang40/anaconda2/envs/arm_diags_env/lib/libnetcdf.13.dylib /Users/zhang40/anaconda2/envs/arm_diags_env/lib/libnetcdf.11.dylib

```

This issue occur because when installing an old version of cdtime (2.10) through conda, some dependencies of it are the latest (i.e.,netcdf), causing above error.
