### ISSUE TITLE
Invalid relative time units

### ISSUE THREAD

**Issue by pochedls** [CDAT/cdms#334]
**Description**
Using cdms2 and cdscan to scan available CMIP data a large number cdscan operations (>6000) return this error: `Invalid relative time units`. All of this data is from the NCAR family of models. 

**To Reproduce**

*Example 1*

> import cdms2
fn = '/p/css03/cmip5_css02/data/cmip5/output1/NCAR/CCSM4/abrupt4xCO2/mon/seaIce/OImon/r1i1p1/sic/1/sic_OImon_CCSM4_abrupt4xCO2_r1i1p1_185001-200012.nc'
f = cdms2.open(fn)
sic = f['sic']
time = sic.getTime()
time.asComponentTime()
---------------------------------------------------------------------------
>ValueError                                Traceback (most recent call last)
<ipython-input-8-63440a219747> in <module>()
----> 1 time.asComponentTime()
~/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/cdms2/axis.py in asComponentTime(self, calendar)
    892             result = []
    893             for val in self[:]:
--> 894                 result.append(cdtime.reltime(val, self.units).tocomp(calendar))
    895         return result
    896
ValueError: Invalid relative time units

*Example 2*

> cdscan -x ~/test.xml /p/css03/cmip5_css02/data/cmip5/output1/NCAR/CCSM4/abrupt4xCO2/mon/seaIce/OImon/r1i1p1/sic/1/*.nc
> Finding common directory ...
Common directory: /p/css03/cmip5_css02/data/cmip5/output1/NCAR/CCSM4/abrupt4xCO2/mon/seaIce/OImon/r1i1p1/sic/1/
Scanning files ...
/p/css03/cmip5_css02/data/cmip5/output1/NCAR/CCSM4/abrupt4xCO2/mon/seaIce/OImon/r1i1p1/sic/1/sic_OImon_CCSM4_abrupt4xCO2_r1i1p1_185001-200012.nc
Setting reference time units to days since 0000-01-01 00:00:00
Traceback (most recent call last):
  File "/export_backup/pochedley1/bin/anaconda2/envs/cdat8/bin/cdscan", line 1840, in <module>
    main(sys.argv)
  File "/export_backup/pochedley1/bin/anaconda2/envs/cdat8/bin/cdscan", line 1310, in main
    calendar)
  File "/export_backup/pochedley1/bin/anaconda2/envs/cdat8/bin/cdscan", line 268, in timeindex
    tval = cdtime.reltime(value, units)
ValueError: Invalid relative time units

**Expected behavior**

Since the time units are `time:units = "days since 0000-01-01 00:00:00" ;`, I would expect that cdms2 would be able to handle this case. 

**Desktop (please complete the following information):**
 - OS: Redhat (crunchy)
 - cdms2 using standard cdat8.0 and cdat8.1 environments

**Comment by pochedls** [comment]
FYI @durack1 - this is the number one reason for cdscan failures. This accounts for 54% of our ~11k cdscan errors.

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 this is a great example of a `cdscan` optimization that would improve functionality greatly, solving 11k files at once!!

Let us know if you need more guidance with this

**Comment by dnadeau4** [comment]
We took away year `0000` since it does not exist in reality.   There was problem with Py3 and year `0000`.   I can revisit that.   E3SM start at year `0001` for PiControl which is right.   `IPSL` has the same issue as `NCAR`, not sure why scientists did this...

**Comment by durack1** [comment]
@dnadeau4 yeah, it's effectively user-error/faulty data, but as it happens so often (~11k in CMIP5), it'd be great for the software to deal with this far better.

On the upside, we have ~11k test cases ready for your bug fix :)

**Comment by pochedls** [comment]
Just to clarify, it is more like 6,000 files (of the 11,000 files we get errors on).

**Comment by dnadeau4** [comment]
I think it is in`cdtime` C functions which is part `libcdms`.   We changed all the tests last year.   The difficulty will be to "add" days to year `0000` and to compare with year `0001` from another file.  At least i can make `cdscan` works for now, but time computation might be off.   I'll keep you in touch.

**Comment by arulalant** [comment]
I am also facing the same problem. As per my understanding, this problem is not in cdscan, but it is in cdms2 (or cdtime).

When I load grib2.ctl file in cdms2,  it time axis does not have unit information. That's why cdscan is throwing "ValueError: Invalid relative time units".

For example in cdat8.1 misses the time unit information:
>>> f['tmp2m'].getTime()
   id: time
   Designated a time axis.
   units:  
   Length: 7
   First:  0.0
   Last:   6.0
   Python id:  0x2b3bfe3d5b50

>>> f['tmp2m'].getTime().asComponentTime()
CDMS error: Error on relative units conversion, string = 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arulalan/miniconda2/envs/cdat8/lib/python2.7/site-packages/cdms2/axis.py", line 894, in asComponentTime
    result.append(cdtime.reltime(val, self.units).tocomp(calendar))
ValueError: Invalid relative time units
>>> 


But for the same grib2.ctl file if access through uvcdat-2.4.0 version it gives proper time information.
>>> f['tmp2m'].getTime()
   id: time
   Designated a time axis.
   units:  hours since 1993-4-16 0:0
   Length: 7
   First:  0.0
   Last:   6.0
   Python id:  0x2b12d7e7b090
>>> f['tmp2m'].getTime().asComponentTime()
[1993-4-16 0:0:0.0, 1993-4-16 1:0:0.0, 1993-4-16 2:0:0.0, 1993-4-16 3:0:0.0, 1993-4-16 4:0:0.0, 1993-4-16 5:0:0.0, 1993-4-16 6:0:0.0]

So some problem happened between uvcdat-2.4.0 version and cdat8 onwards.

By editing time axis unit information while doing cdscan -e option will work for individual grib2.ctl file, but it will not help much if I need to do cdscan of a lot of grib2.ctl files.

I can share the grib2, ctl, idx files if you would like to debug it. Let me know if there any way to fix this problem ?.

Thanks.

**Comment by pochedls** [comment]
@dnadeau4 - when I try this (see: https://github.com/pochedls/xagg/issues/6):

`cdscan -x test.xml -e time.units="days since 0001-01-01" /p/css03/cmip5_css02/data/cmip5/output1/NCAR/CCSM4/abrupt4xCO2/mon/seaIce/OImon/r1i1p1/sic/1/*.nc`

it appears to be off by one year (I think the underlying file starts in 1850-01): 

```
In [1]: import cdms2
In [2]: f = cdms2.open('test.xml')
In [3]: sic = f['sic']
In [4]: sic.getTime().asComponentTime()[0]
Out[4]: 1851-1-16 12:0:0.0
```

Is this a bug? 

I think this generally does not matter for many experiments (e.g., piControl or abrupt4xCO2), but I'd be worried about using this kind of solution generically.

**Comment by pochedls** [comment]
I think I see the issue: it isn't actually updating it to this time unit, it is overriding the original data attribute: 

>     -e newattr:    Add or modify attributes of a file, variable, or
>            axis. The form of 'newattr' is either:
> 
>            'var.attr = value' to modify a variable or attribute, or
>            '.attr = value' to modify a global (file) attribute.
> 
>            In either case, 'value' may be quoted to preserve spaces
>            or force the attribute to be treated as a string. If
>            'value' is not quoted and the first character is a
>            digit, it is converted to integer or
>            floating-point. This option does not modify the input
>            datafiles. See notes and examples below.

**Comment by doutriaux1** [comment]
@pochedls exactly, this is just a workaround to allow you to cdscan it `years since 000` is still invalid.

Did you try one of:  `--time-linear tzero,delta,units[,calendar]` which could work in your case with `months since 1850` ?

**Comment by doutriaux1** [comment]
maybe a combination of both will work in your case?

**Comment by doutriaux1** [comment]
maybe even adding: `-r time_units`

**Comment by pochedls** [comment]
@doutriaux1 - thanks for your suggestions `-r` doesn't seem to work (off by a year still). 

I have avoided `--time-linear` because I worry it isn't generic enough and might lead to problems when we apply it to the entire CMIP5 archive. I also think you'd have to build in a fair amount of logic to correctly set `tzero,delta,units[,calendar]`. 

I don't think I fully understand the root cause of this error. I understand there is no year zero, but I am wondering if there is a place to insert code to handle year zero in these circumstances? 

You had mentioned this has something to do with assumptions about files with a starting year zero (they are a climatology?) - I didn't see something like that [here](https://github.com/CDAT/cdms/blob/master/Lib/cdscan.py).

**Comment by jypeter** [comment]
I also just got the same problem when working with some of our heavily pre-post-processed data files and trying to use `setTimeBoundsMonthly(var)` and `asComponentTime()` (and I think `cdutil.YEAR.climatology`). Remember that in the case of "paleo" or long running experiments, we often don't really care about the actual years

```
   id: time_counter
   Designated a time axis.
   units:  days since 0000-01-01 00:00:00
   Length: 12
   First:  15.5
   Last:   349.7425
   Other axis attributes:
      realtopology: linear
      time_origin: 01-JAN-0000 00:00:00
      calendar: gregorian
      axis: T
   Python id:  0x2ba2c2758710

Traceback (most recent call last):
  File "prepare_plio_data.py", line 42, in <module>
    cdutil.setTimeBoundsMonthly(v_CM6_0k)
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py2/lib/python2.7/site-packages/cdutil-8.0-py3.7.egg/cdutil/times.py", line 1231, in setTimeBoundsMonthly
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py2/lib/python2.7/site-packages/cdutil-8.0-py3.7.egg/cdutil/times.py", line 1215, in setSlabTimeBoundsMonthly
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py2/lib/python2.7/site-packages/cdutil-8.0-py3.7.egg/cdutil/times.py", line 1183, in setAxisTimeBoundsMonthly
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py2/lib/python2.7/site-packages/cdms2/axis.py", line 951, in asComponentTime
    result.append(cdtime.reltime(val, self.units).tocomp(calendar))
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py2/lib/python2.7/site-packages/cdtime/compreltime.py", line 254, in reltime
    return _cdtime.reltime(value, units)
ValueError: Invalid relative time units
```
I also got the same error with `var.getTime().asComponentTime()`. In the case above, there is the extra problem that year **0000** is not really consistent with a _gregorian_ calendar (don't remember when this calendar was first used), but I got a similar error with other files having _noleap_ or _360d_ calendars

My workaround (for now) is to override the time axis' units the following way
```
>>> timax_0k.units
'days since 0000-01-01 00:00:00'
>>> timax_0k.units = 'days since 0001-01-01 00:00:00'
>>> cdutil.setTimeBoundsMonthly(v_CM6_0k)

>>> timax_0k.asComponentTime()
[1-1-16 12:0:0.0, 1-2-15 2:54:36.0, 1-3-16 17:49:12.0, 1-4-16 5:49:12.0, 1-5-16 17:49:12.0, 1-6-16 5:49:12.0, 1-7-16 17:49:12.0, 1-8-16 17:49:12.0, 1-9-16 5:49:12.0, 1-10-16 17:49:12.0, 1-11-16 5:49:12.0, 1-12-16 17:49:12.0]
```

I think a warning (and keep on processing the data) would be nicer for the end user, rather than throwing an exception. It took me a bit of time to figure what was wrong, and the workaround, and I probably know more about this than the average user

**Comment by pochedls** [comment]
@jypeter - could you describe your workaround? 

Since I was working with piControl data (time was largely irrelevant to me), I copied the original files, re-wrote the time units on the copied files using ncatted, created new xml files, and then used the new xml files.

**Comment by jypeter** [comment]
My workaround was to just update the year in time units (change it from `0000` to `0001`) in my script before working on the data. Luckily, getTime() gives you a **pointer** (and not a copy) to the time axis, that you can work on

```
timax = var.getTime()
timax.units = 'days since 0001-01-01 00:00:00'
```

**Comment by durack1** [comment]
@pochedls to be honest, I think if an invalid time units = `'days since 0-1-1'` was found, I would like it to "correct" this automagically to `'days since 1-1-1'`, tell me with a warning, and keep going.. Do you concur?

**Comment by doutriaux1** [comment]
Not that I have much to say about it anymore, but in general "fixing" "broken" things for the user end up in total disaster and loads of blame on the software that altered the user inputs. I think "dying" is better and let the user fix by itself, it's a pain I agree but it forces
  1. The user to realize the data is poor
 2.  The user to generate correct data in the future.

**Comment by pochedls** [comment]
I agree with @doutriaux1, but I think in this case we could probably create a reasonable solution:
* If units are related to year 0000:
     * Throw warning, explaining that the year zero doesn't exist, but cdms will muddle on against its better judgement
     * Read the data in as if it is 'days since 1-1-1'
     * After reading the data in subtract one year from each time step

**Comment by jypeter** [comment]
Tough choice, because I agree with everybody (except possibly `subtract one year from each time step` just above because I'm not sure what @pochedls means by that)

I think the minimum that should be done would be to print something more useful for the end user than just `Invalid relative time units`.

There are lots of ways the relative time units can be wrong! If it's because the year is `0000` instead of `0001` (what would happen with negative years?), say it. It it's because the units use a non allowed time length (e.g. "weekends since 1850-1"), display the list of allowed keywords. And display it _nicely_ like I just suggested in https://github.com/CDAT/cdat/issues/2243

Also, we often have to deal with files that were generated by other people or tools (e.g. ferret, R, nco, cdo, ...) that may be read-only or that we don't want to alter, it would be useful if some tools could keep on doing their job after displaying a warning, in cases like the _0000 year problem_ where it probably won't break too many things.

And if you really want to stop the script, you can also suggest an easy quick fix like the workaround in https://github.com/CDAT/cdms/issues/334#issuecomment-526256898. We know how to do this, but that may not be the case of casual cdms2 users.

**Comment by doutriaux1** [comment]
@pochedls i'm pretty sure subtracting one year would take you to -1-1-1 not 0-1-1

**Comment by pochedls** [comment]
To clarify about the subtract year: If the original data uses units like "months since 0000-01-15" and you alter the units to "months since 0001-01-15" for the purpose of reading the data, then the first time step (suppose it was 1850-01-15 or 1850*12=22,200) would now be interpreted as 1851-01-15 (the second as 1851-02-15, ...). Subtracting one year from each timestep and then re-calculating the relative time (relative to the new units, "months since 0001-01-15," 22,188 for time step one) would give you something usable and more often than not I think the time would be what the original data providers intended.

**Comment by doutriaux1** [comment]
@pochedls I believe time since 0000 was @taylor13 and i poor man implementation for climatologies before CF did a better job. These units are essentially useless. I don't think the time units mean anything except climo in this concept and really shouldn't be used for anything except this. Otherwise 0000 is really a bad time and an error shuold be raised.

**Comment by pochedls** [comment]
@doutriaux1 / @durack1 

What if we replaced the few calls of cdtime.reltime in cdscan with the following function (or something similar). We could add a flag to force cdscan to read in year zero data (using this function). 

```
def getRelTime(time):
	units = time.units
	calInt = time.getCalendar()
	values = time[:]
	# if units use year 0000, cast them to year 0001 units
	# else operate as normal
	if ' 0000-' in units:
		fakeUnits = units.replace(' 0000-', ' 0001-') # valid units for cdtime
		reltime = [] # empty list to store relative time values
		for value in values:
			tr = cdtime.reltime(value, fakeUnits) # get relative time with fake units
			ta = tr.tocomp(calInt) # get component time
			# recast time back assuming year 0000 and year 0001 are off by exactly one
			ct = cdtime.comptime(ta.year - 1, ta.month, ta.day, ta.hour, ta.minute, ta.second) 
			rt = ct.torel(fakeUnits, calInt) # cast back to reltime
			reltime.append(rt)
	else:
		reltime = cdtime.reltime(values, units)

	return reltime
```

**Comment by taylor13** [comment]
I think something like this is probably a good idea, but a clear warning should be given, as suggested by others above.  Also, if after executing the above on a file that had units with year 0000, any subsequent operation to convert time from relative time to calendar time would presumably result in an error, right?

**Comment by pochedls** [comment]
Just noting that @taylor13  and I discussed this. An issue that would also need to be resolved is treatment of the time bounds.

**Comment by taylor13** [comment]
And regarding the time bounds, and tangentially related to the focus of the issue,  it appears that the time-bounds are not saved in the xml files (created by cdscan).  It seems likely that if multiple files then have different "base times" (i.e., reference times in the units attribute), then the bounds obtained from the files will be inconsistent with the times obtained from the xml file.

**Comment by doutriaux1** [comment]
You should let PAul Ullrich know about it, as he is rewriting cdscan

**Comment by durack1** [comment]
@paullric is this an effective way of pulling you into threads?

**Comment by durack1** [comment]
> I am also facing the same problem. As per my understanding, this problem is not in cdscan, but it is in cdms2 (or cdtime).
> 
> When I load grib2.ctl file in cdms2, it time axis does not have unit information. That's why cdscan is throwing "ValueError: Invalid relative time units".

@arulalant there are some problems with grib2 currently that I have hit myself, it's not obvious how to fix the problem

**Comment by paullric** [comment]
> @paullric is this an effective way of pulling you into threads?

I was really close to not reading this email since it was very similar to the stream of E3SM emails that I receive, but I did happen to catch it.  Perhaps we can talk next time I'm around LLNL.

**Comment by gleckler1** [comment]
Somehow we were able to produce cdscan xmls for all CMIP3 data.  Now that we need to reproduce them it fails for some models, like NCAR as noted above.   Lost magic.

**Comment by durack1** [comment]
@gleckler1 the last "routine" cmip3 xmls were generated using [this command line](https://github.com/durack1/cmip3/blob/master/make_cmip3_xml.py#L307) back in August 2013, in the dark days of UVCDAT

**Comment by lee1043** [comment]
I am facing the same issue withe the CESM large ensemble dataset.
```
   id: time
   Designated a time axis.
   units:  days since 0000-1-1
   Length: 2172
   First:  700815.5
   Last:   766849.5
   Other axis attributes:
      realtopology: linear
      long_name: time
      standard_name: time
      calendar: 365_day
      axis: T
   Python id:  0x7f0bcf99d410
```

I like the idea from @pochedls, treating as 0001 then remove 1 year otherwise the data is going to be one year shifted. In my case it won't cause error to set year as 0 or minus, because the first time step of the data is more than a thousand year later from the given "0000-1-1" date. 

Curious to following up how this conversation goes.

**Comment by lee1043** [comment]
Below is my workaround for NCAR's CESM LE, using @pochedls's [code](https://github.com/CDAT/cdms/issues/334#issuecomment-528708407). Thanks to @pochedls.
```python
from __future__ import print_function

import cdms2
import cdtime
import copy
import os

# Open file
file_path = "/work/lee1043/ESGF/ESG_NCAR/CLIVAR_LE/CEMS1-CAM5/mon/pr"
file_name = "pr_Amon_CESM1-CAM5_historical_rcp85_r1i1p1_185001-210012.nc"
var = 'pr'

f = cdms2.open(os.path.join(file_path, file_name))
d = f(var)


def getRelTime(time):
    units = time.units
    calInt = time.getCalendar()
    values = time[:]
    # if units use year 0000, cast them to year 0001 units
    # else operate as normal
    if ' 0000-' in units:
        fakeUnits = units.replace(' 0000-', ' 0001-') # valid units for cdtime
        reltime = [] # empty list to store relative time values
        for value in values:
            tr = cdtime.reltime(value, fakeUnits) # get relative time with fake units
            ta = tr.tocomp(calInt) # get component time
            # recast time back assuming year 0000 and year 0001 are off by exactly one
            ct = cdtime.comptime(ta.year - 1, ta.month, ta.day, ta.hour, ta.minute, ta.second)
            rt = ct.torel(fakeUnits, calInt) # cast back to reltime
            reltime.append(rt)
    else:
        reltime = cdtime.reltime(values, units)

    return reltime


# Get original time axis and adjusted relative time
time = d.getTime()
print('original time:', time)
reltime = getRelTime(time)

# Create new time axis
newtime = copy.copy(time)
newtime[:] = [r.value for r in reltime]
newtime.units = str(reltime[0].units)

# Assign new time axis
d.setAxis(0, newtime)
print('new time:', d.getTime())
```
Result on screen:
```
original time:    id: time
   Designated a time axis.
   units:  days since 0000-1-1
   Length: 3012
   First:  675265.5
   Last:   766849.5
   Other axis attributes:
      realtopology: linear
      long_name: time
      standard_name: time
      calendar: 365_day
      axis: T
   Python id:  0x7f9d36db7a50

new time:    id: time
   Designated a time axis.
   units:  days since 0001-1-1
   Length: 3012
   First:  674900.5
   Last:   766484.5
   Other axis attributes:
      realtopology: linear
      long_name: time
      standard_name: time
      calendar: 365_day
      axis: T
```

**Comment by durack1** [comment]
@pochedls `getRelTime` a candidate for [PCMDI/climlib](https://github.com/PCMDI/climlib)?

**Comment by pochedls** [comment]
@durack1 - Not sure; I view it as hacky and would prefer this be fixed at some lower level in [cdtime](https://github.com/CDAT/cdtime/blob/master/Src/cdtimemodule.c) (so that, e.g., cdscan would work). Does anyone know C?

@dnadeau4 said: 

> We took away year 0000 since it does not exist in reality. There was problem with Py3 and year 0000. I can revisit that. E3SM start at year 0001 for PiControl which is right. IPSL has the same issue as NCAR, not sure why scientists did this...

I couldn't find this particular commit, but it would be nice to deal with year zero and throw a warning rather than an exception. Does anyone want to be a hero?

**Comment by pochedls** [comment]
This was a different version. Is there a better way of dealing generically with either a list or a single value? I think the function above doesn't work if you pass in a value instead of a list or an array. 

```
def getRelTime(values, units, calInt):
  # if float or int, convert to array
  if not isinstance(values, (list, tuple, numpy.ndarray)):
    values = [values]
    singleValue = True
  else:
    singleValue = False
  # if units use year 0000, cast them to year 0001 units
  # else operate as normal
  if ' 0000-' in units:
    fakeUnits = units.replace(' 0000-', ' 0001-') # valid units for cdtime
    reltime = [] # empty list to store relative time values
    for value in values:
      tr = cdtime.reltime(value, fakeUnits) # get relative time with fake units
      ta = tr.tocomp(calInt) # get component time
      # recast time back assuming year 0000 and year 0001 are off by exactly one
      ct = cdtime.comptime(ta.year - 1, ta.month, ta.day, ta.hour, ta.minute, ta.second) 
      rt = ct.torel(fakeUnits, calInt) # cast back to reltime
      reltime.append(rt)
    if singleValue:
      reltime = reltime[0]
  else:
    reltime = cdtime.reltime(values, units)

  return reltime
