### ISSUE TITLE
cdms2.getGrid()/setGrid() doesn't work

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/cdms#42]
``` python
(Pdb) print s.getGrid()
<CurveGrid, id: grid_37, shape: (384, 320)>
(Pdb) heatContent.setGrid(s.getGrid())
*** CDMSError: grid does not match axes for variable variable_524300
(Pdb) heatContent.shape
(60, 384, 320)
(Pdb) print s.shape
(60, 384, 320)
(Pdb) print s.getGrid().shape
(384, 320)
(Pdb) print cdm.createGenericGrid(s.getLatitude(),s.getLongitude(),order='yx')
*** ValueError: could not broadcast input array from shape (384,320) into shape (384)
(Pdb) print cdm.createGenericGrid(s.getLatitude(),s.getLongitude(),order='xy')
*** ValueError: could not broadcast input array from shape (384,320) into shape (384)
(Pdb) print s.getGrid().clone()
<CurveGrid, id: grid_37, shape: (384, 320)>
(Pdb) heatContent.setGrid(s.getGrid().clone())
*** CDMSError: grid does not match axes for variable variable_524300
```

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1707

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 it seems the following also fails, because `grid` is lost during the `MV2.where` operation:
```python
import cdms2 as cdm
import MV2 as mv
# Load basinmask4
fB = cdm.open(modBMatch)
basinmask = fB('basinmask4')
atlMask = basinmask
atlMask = mv.where(basinmask==1,1,0)
pacMask = mv.where(basinmask==2,1,0)
# Load areacella
fA = cdm.open(modAMatch)
areacella = fA('areacella')
atlArea = areacella*atlMask <- this operation loses the grid

atlMask.getGrid()
Out[28]: 
Grid has Python id 0x7f16768b7a90.
Gridtype: generic
Grid shape: (145, 192)
Order: yx

atlArea.getGrid()
Out[29]:

```
And as a consequence I get the following error:
```python
import vcs
x = vcs.init()
x.meshfill(atlArea)
Traceback (most recent call last):
  File "<ipython-input-27-fef7fa5b5005>", line 1, in <module>
    x.meshfill(atlArea)
  File "/export/durack1/anaconda2/envs/uvcdat280/lib/python2.7/site-packages/vcs/Canvas.py", line 1323, in meshfill
    arglist = _determine_arg_list('meshfill', args)
  File "/export/durack1/anaconda2/envs/uvcdat280/lib/python2.7/site-packages/vcs/Canvas.py", line 251, in _determine_arg_list
    raise vcsError("Meshfill requires 2 slab if first slab doesn't have a "
vcsError: Meshfill requires 2 slab if first slab doesn't have a Rectilinear, Curvilinear or Generic Grid type
```
