### ISSUE TITLE
cannot slice string variable from NetCDF file

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/cdms#53]
I have a NetCDF file (ACME output) with a string-valued variable.   With cdms2 I can read one character at a time, but no more.  Thus I can make a FileVariable out of it but not a Transient Variable.  For example:

_>>>_ time_written = f['time_written']
_>>>_ time_written.shape
(1, 8)
_>>>_ time_written[0,1]
'1'
_>>>_ time_written[0,2]
':'
_>>>_ time_written[0,:2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/variable.py", line 82, in **getitem**
    return AbstractVariable.**getitem**(self, key)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 1399, in **getitem**
    return self.getSlice(numericSqueeze=1, raw=0, isitem=1, _speclist)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 656, in getSlice
    result = self.subSlice(_specs, **keys)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 609, in subSlice
    id = self.id)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/tvariable.py", line 270, in **new**
    fill_value = numpy.array(fill_value).astype(dtype),
ValueError: could not convert string to float: N/A

_>>>_ f('time_written')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 45, in **call**
    return v(_args, *_kwargs)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 155, in **call**
    grid=grid)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/selectors.py", line 195, in unmodified_select
    raw=raw)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 759, in subRegion
    return self.subSlice(_slicelist, *_d)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/avariable.py", line 609, in subSlice
    id = self.id)
  File "/Users/painter1/bin/uvcdat-2015.03.25/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/tvariable.py", line 270, in **new**
    fill_value = numpy.array(fill_value).astype(dtype),
ValueError: could not convert string to float: N/A

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1333

**Comment by dnadeau4** [comment]
@painter1 Can you provide me with a file? I think that is fix now.
